import './globals.css';
import { Metadata } from 'next';
import { ClientProvider } from '@/redux/provider';
import { Space_Grotesk } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import Player from './player';
import Sidebar from './sidebar';
import Queue from './queue';
import Search from './search';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

const spaceGrotesk = Space_Grotesk({
   subsets: ['latin'],
   variable: '--font-sans',
   weight: ['500'],
});

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <body className={`font-sans ${spaceGrotesk.variable}`}>
            <ClientProvider>
               <ThemeProvider
                  attribute='class'
                  defaultTheme='dark'
                  enableSystem
               >
                  <main className='relative flex flex-col'>
                     <Search />

                     <Queue />

                     <div className='grid grid-cols-5'>
                        <Sidebar />

                        <section className='border-l-1 col-span-4'>
                           {children}
                        </section>
                     </div>

                     <Player />
                  </main>
               </ThemeProvider>
            </ClientProvider>
         </body>
      </html>
   );
}
